# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rollerball.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10rollerball.proto\x12\nrollerball\".\n\x0bVector3Data\x12\t\n\x01X\x18\x01 \x01(\x02\x12\t\n\x01Y\x18\x02 \x01(\x02\x12\t\n\x01Z\x18\x03 \x01(\x02\"i\n\x0bObservation\x12)\n\x08Position\x18\x01 \x01(\x0b\x32\x17.rollerball.Vector3Data\x12/\n\x0eTargetPosition\x18\x02 \x01(\x0b\x32\x17.rollerball.Vector3Data\"0\n\x06\x41\x63tion\x12&\n\x05\x46orce\x18\x01 \x01(\x0b\x32\x17.rollerball.Vector3Data\",\n\x0cRewardSignal\x12\x0e\n\x06reward\x18\x01 \x01(\x02\x12\x0c\n\x04\x64one\x18\x02 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rollerball_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTOR3DATA']._serialized_start=32
  _globals['_VECTOR3DATA']._serialized_end=78
  _globals['_OBSERVATION']._serialized_start=80
  _globals['_OBSERVATION']._serialized_end=185
  _globals['_ACTION']._serialized_start=187
  _globals['_ACTION']._serialized_end=235
  _globals['_REWARDSIGNAL']._serialized_start=237
  _globals['_REWARDSIGNAL']._serialized_end=281
# @@protoc_insertion_point(module_scope)
